name: Dart CI

on:
  push:
    tags: 
    - '*'
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'stable'
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    - run: flutter doctor && flutter channel beta && flutter version && echo $KEY_JKS  | base64 -d > ./android/key.jks && ls -la && flutter pub get && flutter build apk --release
    - uses: siristechnology/action-create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        RELEASE_FILE_PATH: build/outputs/apk/release/app-release.apk
        RELEASE_TITLE: "New Build"
